#! /usr/bin/perl

use lib qw(. /var/local/libdata/perl5);

use strict;
use CGI;
use STG_TPL;

my $q = new CGI;

eval
{
	my (%counts, %fids);
	my (@missing, @ids);
	my ($day, $filename, $idx, $fid);
	my ($type, $fid, $count, $rule);
	for ($day = 0; $day <= 6; $day++)
	{
		$filename = '/var/log/procmailreport.' . $day;
		if (! -s $filename)
		{
			push(@missing, $day+1);
			last;
		}
		if (!open(REPORT, "< $filename"))
		{
			die "Cannot open $filename";
		}
		while(<REPORT>)
		{
			chomp;
			($type, $fid, $count, $rule) = split(/\t/, $_, 4);
			if (defined($counts{$type}{$rule}))
			{
				$counts{$type}{$rule} += $count;
			}
			else
			{
				$counts{$type}{$rule} = $count;
			}
			if (defined($fids{$type}))
			{
				my @i = split(/,/, $fid);
				@ids = split(/,/, $fids{$type});
				for($idx = 0; $idx < @i; $idx++)
				{
					if (0 >= grep { $_ == $i[$idx] } @ids)
					{
						push(@ids, $i[$idx]);
					}
				}
				$fid = join(',', @ids);
			}
			$fids{$type} = $fid;
		}
		close(REPORT);
	}
			
	if (@missing > 0)
	{
		print $q->header,
			$q->start_html('Email Spam Filter Log Report');

		my $days = join(", ", @missing);
		print "<h2><font face=Arial color=#26589E>Missing Email Spam Filter 7 Days Log Report for day: $days</font></h2>\n";

		print $q->end_html;
	}
	else
	{
		print $q->header,
			$q->start_html('Email Spam Filter 7 Days Log Report');
		print <<EOM;

<h2><font face="Arial" color="#26589E">Email Spam Filter 7 Days Log Report</font></h2>
<div align="center">
  <center>
  <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#26589E" width="575">
    <tr>
      <td bgcolor="#FEFAE7" height="21">
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="575">
          <tr>
            <td width="120">&nbsp;<b><font face="Arial" size="2" color="#26589E">Filter Type:</font></b></td>
            <td width="45">
            <p align="right"><b><font face="Arial" size="2" color="#26589E">#&nbsp;</font></b></td>
            <td width="334"><b><font face="Arial" size="2" color="#26589E">
            Filter Details:</font></b></td>
            <td align="right" width="96">&nbsp;</td>
          </tr>
        </table>
        </center>
      </td>
    </tr>
    <tr>
      <td>
        <center>
        <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" bordercolor="#111111" width="575">
          <tr>
            <td colspan="4" height=14>
            <img border="0" src="/drm/spacer_1pixel.gif" width="1" height="1"></td>
          </tr>
EOM

		my $out = 0;
		foreach $type (keys %counts)
		{
			if ($out > 0)
			{
				print <<EOM;
          <tr>
            <td width="575" colspan="4" height="25">
            <hr color="#26589E" width="97%" noshade size="1">
            </td>
          </tr>
EOM
			}

			my ($countstg) = '';
			my ($rulestg) = '';
			foreach $rule (sort {$counts{$type}{$b} <=> $counts{$type}{$a}} keys %{$counts{$type}})
			{
				$countstg .= "              $counts{$type}{$rule}&nbsp;<br>\n";
				$rule =~ s/&/&amp;/g;
				$rule =~ s/</&lt;/g;
				$rule =~ s/>/&gt;/g;
				$rulestg .= "              $rule<br>\n";
			}
			$fid = $fids{$type};
			$type =~ s/&/&amp;/g;
			$type =~ s/</&lt;/g;
			$type =~ s/>/&gt;/g;
			print <<EOM;
          <tr>
            <td width="118" valign="top">&nbsp;<font face="Arial" size="2" color="#26589E">$type</font></td>
            <td width="45" valign="top" align="right"><font face="Arial" size="2" color="#26589E">
$countstg
            </font></td>
            <td width="364" valign="top"><font face="Arial" size="2" color="#26589E">
$rulestg
            </font></td>
            <td width="48" valign="top">
            <p align="right"><a href=/admin/filterdetail?a+$fid><font color="#26589E">Details</font></a>&nbsp;&nbsp;</td>
          </tr>
EOM
			$out++;
		}

print <<EOM;
          <tr>
            <td colspan="4" height=14>
            <img border="0" src="/drm/spacer_1pixel.gif" width="1" height="1"></td>
          </tr>
        </table>
        </center>
      </td>
    </tr>
  </table>
  </center>
</div>
</body>
EOM
		print $q->end_html;
	}
};

if ($@)
{
	my $errmsg = $@;
	print 'Content-type: text/html', "\n\n";
	print "Error Viewing Email Spam Filter Log\n";
}

exit 0;
