#! /usr/bin/perl

use strict;
use DB_File;

my %db;
my $db_name = "/var/local/mail/kachun/filter.db";

tie (%db, "DB_File", $db_name, O_RDWR|O_CREAT, 0644, $DB_HASH) or
	die "Cannot open $db_name";


my $now = time;

untie %db;
