#! /usr/bin/perl

use CGI qw(:standard);
use strict;

use drmdef;

$| = 1;
print header;

my $headerheight = '90';

use vars qw($DEBUG);

my $BORDER = $DEBUG ? 1 : 0;

my $pathinfo = $ENV{PATH_INFO};
my $idx = ($pathinfo =~ /^\/([^\/]*)/) ? 0 + $1 : 0;

my @link = ($BINDIR . 'frmaddbkmn', $BINDIR . 'frmaddbked',
			$HTDIR . 'addbkhelp.html');
$idx = scalar(@link) - 1 if $idx > scalar(@link); 
my $preflink = $link[$idx];

my $page = ($idx>0) ? sprintf("/%d", $idx) : '';

print <<EOM;
<frameset rows="$headerheight,*" framespacing=0 frameborder=$BORDER border=1>
	<frame name=DRMAddBkHeader marginheight=0 marginwidth=0 scrolling=no NORESIZE src=${BINDIR}frmaddbkhd$page>
	<frame name=DRMAddBkBody marginheight=5 marginwidth=5 src=$preflink>
</frameset>
EOM

exit 0;
