#! /usr/bin/perl

use CGI qw(:standard);
use strict;

use drmdef;

$| = 1;
print header;

my ($opt) = $ARGV[0];
print "<html>\n";
if ($opt eq '-h')
{
	print <<EOM;
<body bgcolor=#EAEFF8>
<table border=0 cellpadding=0 cellspacing=0 height=7 width=100%>
<tr>
<td bgcolor="#EAEFF8" height=7><img src=${IMGDIR}spacer_1pixel.gif width=1 height=1></td>
</tr>
</table>
EOM
}
else
{
	print <<EOM;
<body>
&nbsp;<br>
EOM
}

print <<EOM;
</body>
</html>
EOM

exit 0;
